/**
 * Medicare Advantage Plan Seed Data
 * Based on comprehensive US health insurance plan database framework
 * Data sources: Data.CMS.gov, Medicare.gov Plan Finder
 */

import { getDb } from '../client';
import { medicareAdvantagePlans } from '../schema/insurance-costs';

export async function seedMedicareAdvantagePlans() {
  console.log('🏥 Seeding Medicare Advantage plans...');

  const db = getDb();

  // Clear existing data
  await db.delete(medicareAdvantagePlans);

  const planYear = 2025;

  const plans = [
    // California - High MA penetration
    {
      state: 'CA',
      county: 'Los Angeles',
      zipCode: '90001',
      planName: 'UnitedHealthcare Group Medicare Advantage (HMO)',
      carrier: 'UnitedHealthcare',
      planType: 'HMO',
      monthlyPremium: '0.00', // Many MA plans have $0 premium
      medicalDeductible: '0.00',
      drugDeductible: '0.00',
      oopMaximum: '6700.00',
      dentalCoverage: true,
      visionCoverage: true,
      hearingCoverage: true,
      partDCoverage: true,
      serviceArea: JSON.stringify(['Los Angeles', 'Orange', 'San Bernardino']),
      networkSize: 'large',
      requiresReferrals: true,
      starRating: '4.5',
      planYear,
      contractId: 'H0564',
      planId: '001',
      isActive: true,
    },
    {
      state: 'CA',
      county: 'Los Angeles',
      zipCode: '90001',
      planName: 'Kaiser Permanente Senior Advantage (HMO)',
      carrier: 'Kaiser Permanente',
      planType: 'HMO',
      monthlyPremium: '0.00',
      medicalDeductible: '0.00',
      drugDeductible: '100.00',
      oopMaximum: '5900.00',
      dentalCoverage: true,
      visionCoverage: true,
      hearingCoverage: true,
      partDCoverage: true,
      serviceArea: JSON.stringify(['Los Angeles', 'Riverside', 'San Diego']),
      networkSize: 'medium',
      requiresReferrals: true,
      starRating: '5.0',
      planYear,
      contractId: 'H0489',
      planId: '002',
      isActive: true,
    },
    {
      state: 'CA',
      county: 'San Diego',
      zipCode: '92101',
      planName: 'Anthem MediBlue Plus (HMO)',
      carrier: 'Anthem',
      planType: 'HMO',
      monthlyPremium: '29.00',
      medicalDeductible: '0.00',
      drugDeductible: '0.00',
      oopMaximum: '6700.00',
      dentalCoverage: true,
      visionCoverage: true,
      hearingCoverage: false,
      partDCoverage: true,
      serviceArea: JSON.stringify(['San Diego']),
      networkSize: 'medium',
      requiresReferrals: false,
      starRating: '4.0',
      planYear,
      contractId: 'H1287',
      planId: '003',
      isActive: true,
    },

    // Florida - Largest MA market in the nation
    {
      state: 'FL',
      county: 'Miami-Dade',
      zipCode: '33101',
      planName: 'Humana Gold Plus HMO',
      carrier: 'Humana',
      planType: 'HMO',
      monthlyPremium: '0.00',
      medicalDeductible: '0.00',
      drugDeductible: '0.00',
      oopMaximum: '7550.00',
      dentalCoverage: true,
      visionCoverage: true,
      hearingCoverage: true,
      partDCoverage: true,
      serviceArea: JSON.stringify(['Miami-Dade', 'Broward', 'Palm Beach']),
      networkSize: 'large',
      requiresReferrals: true,
      starRating: '4.5',
      planYear,
      contractId: 'H1036',
      planId: '004',
      isActive: true,
    },
    {
      state: 'FL',
      county: 'Miami-Dade',
      zipCode: '33101',
      planName: 'WellCare Giveback (HMO)',
      carrier: 'WellCare',
      planType: 'HMO',
      monthlyPremium: '0.00', // Part B giveback plan
      medicalDeductible: '0.00',
      drugDeductible: '75.00',
      oopMaximum: '8300.00',
      dentalCoverage: true,
      visionCoverage: true,
      hearingCoverage: true,
      partDCoverage: true,
      serviceArea: JSON.stringify(['Miami-Dade', 'Broward']),
      networkSize: 'medium',
      requiresReferrals: true,
      starRating: '3.5',
      planYear,
      contractId: 'H3259',
      planId: '005',
      isActive: true,
    },
    {
      state: 'FL',
      county: 'Pinellas',
      zipCode: '33701',
      planName: 'Florida Blue Medicare (PPO)',
      carrier: 'Florida Blue',
      planType: 'PPO',
      monthlyPremium: '49.00',
      medicalDeductible: '250.00',
      drugDeductible: '100.00',
      oopMaximum: '6700.00',
      dentalCoverage: true,
      visionCoverage: true,
      hearingCoverage: true,
      partDCoverage: true,
      serviceArea: JSON.stringify(['Pinellas', 'Hillsborough', 'Pasco']),
      networkSize: 'large',
      requiresReferrals: false,
      starRating: '4.0',
      planYear,
      contractId: 'H1035',
      planId: '006',
      isActive: true,
    },

    // Texas
    {
      state: 'TX',
      county: 'Harris',
      zipCode: '77001',
      planName: 'Cigna True Choice Medicare (PPO)',
      carrier: 'Cigna',
      planType: 'PPO',
      monthlyPremium: '0.00',
      medicalDeductible: '0.00',
      drugDeductible: '0.00',
      oopMaximum: '6700.00',
      dentalCoverage: true,
      visionCoverage: true,
      hearingCoverage: false,
      partDCoverage: true,
      serviceArea: JSON.stringify(['Harris', 'Fort Bend', 'Montgomery']),
      networkSize: 'large',
      requiresReferrals: false,
      starRating: '4.5',
      planYear,
      contractId: 'H2430',
      planId: '007',
      isActive: true,
    },
    {
      state: 'TX',
      county: 'Dallas',
      zipCode: '75201',
      planName: 'Aetna Medicare Eagle (HMO)',
      carrier: 'Aetna',
      planType: 'HMO',
      monthlyPremium: '0.00',
      medicalDeductible: '0.00',
      drugDeductible: '0.00',
      oopMaximum: '7550.00',
      dentalCoverage: true,
      visionCoverage: true,
      hearingCoverage: true,
      partDCoverage: true,
      serviceArea: JSON.stringify(['Dallas', 'Tarrant', 'Collin']),
      networkSize: 'large',
      requiresReferrals: true,
      starRating: '4.0',
      planYear,
      contractId: 'H5521',
      planId: '008',
      isActive: true,
    },

    // Arizona - Snowbird destination
    {
      state: 'AZ',
      county: 'Maricopa',
      zipCode: '85001',
      planName: 'UnitedHealthcare Dual Complete (HMO SNP)',
      carrier: 'UnitedHealthcare',
      planType: 'SNP', // Special Needs Plan for dual-eligible
      monthlyPremium: '0.00',
      medicalDeductible: '0.00',
      drugDeductible: '0.00',
      oopMaximum: '4900.00',
      dentalCoverage: true,
      visionCoverage: true,
      hearingCoverage: true,
      partDCoverage: true,
      serviceArea: JSON.stringify(['Maricopa', 'Pima']),
      networkSize: 'large',
      requiresReferrals: true,
      starRating: '4.5',
      planYear,
      contractId: 'H3471',
      planId: '009',
      isActive: true,
    },
    {
      state: 'AZ',
      county: 'Maricopa',
      zipCode: '85001',
      planName: 'Humana Honor (PPO)',
      carrier: 'Humana',
      planType: 'PPO',
      monthlyPremium: '65.00',
      medicalDeductible: '0.00',
      drugDeductible: '100.00',
      oopMaximum: '5900.00',
      dentalCoverage: true,
      visionCoverage: true,
      hearingCoverage: true,
      partDCoverage: true,
      serviceArea: JSON.stringify(['Maricopa', 'Pinal', 'Yavapai']),
      networkSize: 'large',
      requiresReferrals: false,
      starRating: '4.5',
      planYear,
      contractId: 'H5216',
      planId: '010',
      isActive: true,
    },

    // New York
    {
      state: 'NY',
      county: 'New York',
      zipCode: '10001',
      planName: 'EmblemHealth VIP Premier (HMO)',
      carrier: 'EmblemHealth',
      planType: 'HMO',
      monthlyPremium: '0.00',
      medicalDeductible: '0.00',
      drugDeductible: '0.00',
      oopMaximum: '6700.00',
      dentalCoverage: true,
      visionCoverage: true,
      hearingCoverage: true,
      partDCoverage: true,
      serviceArea: JSON.stringify(['New York', 'Bronx', 'Kings', 'Queens']),
      networkSize: 'large',
      requiresReferrals: true,
      starRating: '4.0',
      planYear,
      contractId: 'H3330',
      planId: '011',
      isActive: true,
    },
    {
      state: 'NY',
      county: 'New York',
      zipCode: '10001',
      planName: 'United AARP Medicare Advantage (HMO-POS)',
      carrier: 'UnitedHealthcare',
      planType: 'HMO',
      monthlyPremium: '0.00',
      medicalDeductible: '0.00',
      drugDeductible: '0.00',
      oopMaximum: '7550.00',
      dentalCoverage: true,
      visionCoverage: true,
      hearingCoverage: false,
      partDCoverage: true,
      serviceArea: JSON.stringify(['New York', 'Nassau', 'Suffolk', 'Westchester']),
      networkSize: 'large',
      requiresReferrals: false,
      starRating: '4.5',
      planYear,
      contractId: 'H3347',
      planId: '012',
      isActive: true,
    },

    // Pennsylvania - Additional multi-state coverage
    {
      state: 'PA',
      county: 'Philadelphia',
      zipCode: '19101',
      planName: 'Independence Blue Cross (HMO)',
      carrier: 'Independence Blue Cross',
      planType: 'HMO',
      monthlyPremium: '0.00',
      medicalDeductible: '0.00',
      drugDeductible: '0.00',
      oopMaximum: '6700.00',
      dentalCoverage: true,
      visionCoverage: true,
      hearingCoverage: true,
      partDCoverage: true,
      serviceArea: JSON.stringify(['Philadelphia', 'Bucks', 'Chester', 'Delaware', 'Montgomery']),
      networkSize: 'large',
      requiresReferrals: true,
      starRating: '4.0',
      planYear,
      contractId: 'H3954',
      planId: '013',
      isActive: true,
    },

    // North Carolina
    {
      state: 'NC',
      county: 'Mecklenburg',
      zipCode: '28201',
      planName: 'Blue Medicare Advantage (PPO)',
      carrier: 'Blue Cross Blue Shield of North Carolina',
      planType: 'PPO',
      monthlyPremium: '39.00',
      medicalDeductible: '0.00',
      drugDeductible: '100.00',
      oopMaximum: '6700.00',
      dentalCoverage: true,
      visionCoverage: true,
      hearingCoverage: true,
      partDCoverage: true,
      serviceArea: JSON.stringify(['Mecklenburg', 'Gaston', 'Union', 'Cabarrus']),
      networkSize: 'large',
      requiresReferrals: false,
      starRating: '4.5',
      planYear,
      contractId: 'H5321',
      planId: '014',
      isActive: true,
    },

    // Washington State
    {
      state: 'WA',
      county: 'King',
      zipCode: '98101',
      planName: 'Kaiser Permanente Medicare Advantage (HMO)',
      carrier: 'Kaiser Permanente',
      planType: 'HMO',
      monthlyPremium: '0.00',
      medicalDeductible: '0.00',
      drugDeductible: '0.00',
      oopMaximum: '5900.00',
      dentalCoverage: true,
      visionCoverage: true,
      hearingCoverage: true,
      partDCoverage: true,
      serviceArea: JSON.stringify(['King', 'Snohomish', 'Pierce']),
      networkSize: 'medium',
      requiresReferrals: true,
      starRating: '5.0',
      planYear,
      contractId: 'H3956',
      planId: '015',
      isActive: true,
    },
  ];

  await db.insert(medicareAdvantagePlans).values(plans);

  console.log(`✅ Seeded ${plans.length} Medicare Advantage plans`);
}
