/**
 * Carrier Contact Information and State Metadata Seed Data
 * Based on comprehensive US health insurance plan database framework
 */

import { getDb } from '../client';
import { multiStateCarriers, states } from '../schema/state-metadata';

export async function seedCarriersAndStates() {
  console.log('🏥 Seeding carrier contact information and state metadata...');

  const db = getDb();

  // Clear existing data
  await db.delete(states);
  await db.delete(multiStateCarriers);

  // Multi-State Carriers (from PDF data)
  const carriers = [
    {
      carrierName: 'UnitedHealthcare',
      parentCompany: 'UnitedHealth Group',
      states: JSON.stringify(['CA', 'FL', 'TX', 'NY', 'AZ', 'PA', 'NC', 'WA', 'IL', 'OH', 'GA', 'MI', 'NJ', 'VA', 'CO']),
      totalStates: 50,
      isTrulyNational: true,
      hasNetworkReciprocity: true,
      reciprocityDetails: 'UnitedHealthcare offers network reciprocity across states for PPO plans. HMO plans require in-network care in the home state.',
      offersACA: true,
      offersMedicare: true,
      offersMedicaid: true,
      offersEmployer: true,
      website: 'https://www.uhc.com',
      customerServicePhone: '1-800-328-5979',
      planYear: 2025,
      isActive: true,
    },
    {
      carrierName: 'Anthem',
      parentCompany: 'Elevance Health',
      states: JSON.stringify(['CA', 'NY', 'CO', 'CT', 'GA', 'IN', 'KY', 'ME', 'MO', 'NV', 'NH', 'OH', 'VA', 'WI']),
      totalStates: 14,
      isTrulyNational: false,
      hasNetworkReciprocity: true,
      reciprocityDetails: 'Blue Cross Blue Shield network allows cross-state coverage through BlueCard program.',
      offersACA: true,
      offersMedicare: true,
      offersMedicaid: true,
      offersEmployer: true,
      website: 'https://www.anthem.com',
      customerServicePhone: '1-833-707-6106',
      planYear: 2025,
      isActive: true,
    },
    {
      carrierName: 'Cigna',
      parentCompany: 'The Cigna Group',
      states: JSON.stringify(['TX', 'FL', 'AZ', 'TN', 'NC', 'VA', 'IL', 'GA', 'CO', 'PA']),
      totalStates: 15,
      isTrulyNational: false,
      hasNetworkReciprocity: true,
      reciprocityDetails: 'Cigna PPO plans offer nationwide network coverage. HMO plans are state-specific.',
      offersACA: true,
      offersMedicare: true,
      offersMedicaid: false,
      offersEmployer: true,
      website: 'https://www.cigna.com',
      customerServicePhone: '1-800-244-6224',
      planYear: 2025,
      isActive: true,
    },
    {
      carrierName: 'Humana',
      parentCompany: 'Humana Inc.',
      states: JSON.stringify(['FL', 'TX', 'AZ', 'OH', 'KY', 'TN', 'GA', 'SC', 'LA', 'IL', 'WI']),
      totalStates: 18,
      isTrulyNational: false,
      hasNetworkReciprocity: true,
      reciprocityDetails: 'Humana offers nationwide PPO coverage with regional HMO networks.',
      offersACA: true,
      offersMedicare: true,
      offersMedicaid: false,
      offersEmployer: true,
      website: 'https://www.humana.com',
      customerServicePhone: '1-800-448-6262',
      planYear: 2025,
      isActive: true,
    },
    {
      carrierName: 'Kaiser Permanente',
      parentCompany: 'Kaiser Foundation Health Plan',
      states: JSON.stringify(['CA', 'WA', 'OR', 'CO', 'HI', 'MD', 'VA', 'DC']),
      totalStates: 8,
      isTrulyNational: false,
      hasNetworkReciprocity: false,
      reciprocityDetails: 'Kaiser offers emergency coverage nationwide, but routine care requires in-network providers in home state.',
      offersACA: true,
      offersMedicare: true,
      offersMedicaid: true,
      offersEmployer: true,
      website: 'https://www.kp.org',
      customerServicePhone: '1-800-464-4000',
      planYear: 2025,
      isActive: true,
    },
    {
      carrierName: 'Blue Cross Blue Shield',
      parentCompany: 'Blue Cross Blue Shield Association',
      states: JSON.stringify(['TX', 'FL', 'NC', 'IL', 'MI', 'AZ', 'MA', 'MN', 'LA', 'NM', 'OK', 'SC', 'AL', 'TN']),
      totalStates: 36,
      isTrulyNational: false,
      hasNetworkReciprocity: true,
      reciprocityDetails: 'BlueCard program provides nationwide coverage across all BCBS affiliates.',
      offersACA: true,
      offersMedicare: true,
      offersMedicaid: true,
      offersEmployer: true,
      website: 'https://www.bcbs.com',
      customerServicePhone: '1-888-630-2583',
      planYear: 2025,
      isActive: true,
    },
    {
      carrierName: 'Centene',
      parentCompany: 'Centene Corporation',
      states: JSON.stringify(['FL', 'TX', 'AZ', 'CA', 'GA', 'IL', 'IN', 'KS', 'MO', 'NC', 'OH', 'SC', 'WA', 'WI']),
      totalStates: 30,
      isTrulyNational: false,
      hasNetworkReciprocity: false,
      reciprocityDetails: 'Ambetter plans are state-specific with limited cross-state coverage.',
      offersACA: true,
      offersMedicare: true,
      offersMedicaid: true,
      offersEmployer: false,
      website: 'https://www.centene.com',
      customerServicePhone: '1-877-687-1196',
      planYear: 2025,
      isActive: true,
    },
    {
      carrierName: 'Aetna',
      parentCompany: 'CVS Health',
      states: JSON.stringify(['TX', 'FL', 'CA', 'NY', 'PA', 'IL', 'OH', 'GA', 'NC', 'VA', 'AZ', 'NJ']),
      totalStates: 20,
      isTrulyNational: false,
      hasNetworkReciprocity: true,
      reciprocityDetails: 'Aetna PPO plans offer nationwide coverage. HMO plans require in-network care.',
      offersACA: true,
      offersMedicare: true,
      offersMedicaid: true,
      offersEmployer: true,
      website: 'https://www.aetna.com',
      customerServicePhone: '1-800-872-3862',
      planYear: 2025,
      isActive: true,
    },
    {
      carrierName: 'Oscar Health',
      parentCompany: 'Oscar Health, Inc.',
      states: JSON.stringify(['NY', 'CA', 'TX', 'FL', 'AZ', 'OH', 'TN', 'PA', 'VA']),
      totalStates: 9,
      isTrulyNational: false,
      hasNetworkReciprocity: false,
      reciprocityDetails: 'Oscar offers telemedicine nationwide but in-person care requires in-network providers.',
      offersACA: true,
      offersMedicare: false,
      offersMedicaid: false,
      offersEmployer: true,
      website: 'https://www.hioscar.com',
      customerServicePhone: '1-855-672-2788',
      planYear: 2025,
      isActive: true,
    },
    {
      carrierName: 'Molina Healthcare',
      parentCompany: 'Molina Healthcare, Inc.',
      states: JSON.stringify(['CA', 'FL', 'TX', 'WA', 'OH', 'IL', 'MI', 'NM', 'SC', 'UT', 'WI']),
      totalStates: 15,
      isTrulyNational: false,
      hasNetworkReciprocity: false,
      reciprocityDetails: 'Molina plans are state-specific with focus on Medicaid and ACA marketplace.',
      offersACA: true,
      offersMedicare: true,
      offersMedicaid: true,
      offersEmployer: false,
      website: 'https://www.molinahealthcare.com',
      customerServicePhone: '1-888-898-7969',
      planYear: 2025,
      isActive: true,
    },
  ];

  await db.insert(multiStateCarriers).values(carriers);
  console.log(`  ✓ Inserted ${carriers.length} multi-state carriers`);

  // State Metadata (from PDF data)
  const statesData = [
    {
      stateCode: 'CA',
      stateName: 'California',
      exchangeType: 'state',
      exchangeName: 'Covered California',
      exchangeWebsite: 'https://www.coveredca.com',
      exchangePhone: '1-800-300-1506',
      medicaidExpanded: true,
      medicaidExpansionDate: new Date('2014-01-01'),
      medicaidIncomeLimitAdults: '138.00',
      medicaidIncomeLimitChildren: '266.00',
      medicaidWebsite: 'https://www.dhcs.ca.gov/medi-cal',
      medicaidProgramName: 'Medi-Cal',
      chipIncomeLimitChildren: '266.00',
      chipWebsite: 'https://www.dhcs.ca.gov/medi-cal',
      chipProgramName: 'Medi-Cal (includes CHIP)',
      dominantCarriers: JSON.stringify([
        { name: 'Kaiser Permanente', marketShare: 28.5 },
        { name: 'Blue Shield of California', marketShare: 22.3 },
        { name: 'Health Net', marketShare: 18.7 },
      ]),
      averageCarrierCount: 12,
      marketConcentration: 'medium',
      averagePremiumIndex: '1.150',
      averagePremiumSingleAdult: '520.00',
      averagePremiumFamily: '1450.00',
      individualMandate: true,
      individualMandatePenalty: 'Minimum $850 or 2.5% of household income',
      openEnrollmentStart: '11-01',
      openEnrollmentEnd: '01-31',
      hasExtendedEnrollment: true,
      allowsShortTermPlans: false,
      shortTermMaxDuration: 0,
      requiresNavigators: true,
      navigatorHotline: '1-800-300-1506',
      stateInsuranceDepartment: 'California Department of Insurance',
      insuranceDepartmentWebsite: 'https://www.insurance.ca.gov',
      population: 39538223,
      totalCounties: 58,
      urbanPercentage: '95.00',
      dataYear: 2025,
      lastVerified: new Date(),
      notes: '1.98 million marketplace enrollees. Strong state-based exchange with robust subsidies.',
    },
    {
      stateCode: 'FL',
      stateName: 'Florida',
      exchangeType: 'federal',
      exchangeName: 'Healthcare.gov',
      exchangeWebsite: 'https://www.healthcare.gov',
      exchangePhone: '1-800-318-2596',
      medicaidExpanded: false,
      medicaidExpansionDate: null,
      medicaidIncomeLimitAdults: '0.00', // No expansion
      medicaidIncomeLimitChildren: '206.00',
      medicaidWebsite: 'https://www.myflfamilies.com/service-programs/access-florida-food-medical-assistance-cash/',
      medicaidProgramName: 'Florida Medicaid',
      chipIncomeLimitChildren: '206.00',
      chipWebsite: 'https://www.floridakidcare.org',
      chipProgramName: 'Florida KidCare',
      dominantCarriers: JSON.stringify([
        { name: 'Florida Blue', marketShare: 35.2 },
        { name: 'Molina Healthcare', marketShare: 15.8 },
        { name: 'Ambetter from Sunshine Health', marketShare: 12.4 },
      ]),
      averageCarrierCount: 10,
      marketConcentration: 'high',
      averagePremiumIndex: '1.080',
      averagePremiumSingleAdult: '495.00',
      averagePremiumFamily: '1380.00',
      individualMandate: false,
      individualMandatePenalty: null,
      openEnrollmentStart: '11-01',
      openEnrollmentEnd: '01-15',
      hasExtendedEnrollment: false,
      allowsShortTermPlans: true,
      shortTermMaxDuration: 364,
      requiresNavigators: false,
      navigatorHotline: '1-800-318-2596',
      stateInsuranceDepartment: 'Florida Office of Insurance Regulation',
      insuranceDepartmentWebsite: 'https://www.floir.com',
      population: 21538187,
      totalCounties: 67,
      urbanPercentage: '91.00',
      dataYear: 2025,
      lastVerified: new Date(),
      notes: '4.7 million marketplace enrollees (highest in nation). Large retiree and snowbird population.',
    },
    {
      stateCode: 'TX',
      stateName: 'Texas',
      exchangeType: 'federal',
      exchangeName: 'Healthcare.gov',
      exchangeWebsite: 'https://www.healthcare.gov',
      exchangePhone: '1-800-318-2596',
      medicaidExpanded: false,
      medicaidExpansionDate: null,
      medicaidIncomeLimitAdults: '0.00',
      medicaidIncomeLimitChildren: '201.00',
      medicaidWebsite: 'https://www.hhs.texas.gov/services/health/medicaid-chip',
      medicaidProgramName: 'Texas Medicaid',
      chipIncomeLimitChildren: '201.00',
      chipWebsite: 'https://www.chipmedicaid.org',
      chipProgramName: 'CHIP',
      dominantCarriers: JSON.stringify([
        { name: 'Blue Cross Blue Shield of Texas', marketShare: 25.6 },
        { name: 'Ambetter from Superior HealthPlan', marketShare: 22.1 },
        { name: 'Cigna', marketShare: 14.3 },
      ]),
      averageCarrierCount: 16,
      marketConcentration: 'low',
      averagePremiumIndex: '1.020',
      averagePremiumSingleAdult: '475.00',
      averagePremiumFamily: '1320.00',
      individualMandate: false,
      individualMandatePenalty: null,
      openEnrollmentStart: '11-01',
      openEnrollmentEnd: '01-15',
      hasExtendedEnrollment: false,
      allowsShortTermPlans: true,
      shortTermMaxDuration: 364,
      requiresNavigators: false,
      navigatorHotline: '1-800-318-2596',
      stateInsuranceDepartment: 'Texas Department of Insurance',
      insuranceDepartmentWebsite: 'https://www.tdi.texas.gov',
      population: 29145505,
      totalCounties: 254,
      urbanPercentage: '84.00',
      dataYear: 2025,
      lastVerified: new Date(),
      notes: '4 million marketplace enrollees. 16 carriers offering plans - most competitive market.',
    },
    {
      stateCode: 'NY',
      stateName: 'New York',
      exchangeType: 'state',
      exchangeName: 'NY State of Health',
      exchangeWebsite: 'https://nystateofhealth.ny.gov',
      exchangePhone: '1-855-355-5777',
      medicaidExpanded: true,
      medicaidExpansionDate: new Date('2014-01-01'),
      medicaidIncomeLimitAdults: '138.00',
      medicaidIncomeLimitChildren: '223.00',
      medicaidWebsite: 'https://www.health.ny.gov/health_care/medicaid/',
      medicaidProgramName: 'New York Medicaid',
      chipIncomeLimitChildren: '223.00',
      chipWebsite: 'https://www.health.ny.gov/health_care/child_health_plus/',
      chipProgramName: 'Child Health Plus',
      dominantCarriers: JSON.stringify([
        { name: 'Oscar Health', marketShare: 28.3 },
        { name: 'EmblemHealth', marketShare: 24.7 },
        { name: 'Anthem', marketShare: 18.2 },
      ]),
      averageCarrierCount: 8,
      marketConcentration: 'medium',
      averagePremiumIndex: '1.280',
      averagePremiumSingleAdult: '620.00',
      averagePremiumFamily: '1720.00',
      individualMandate: false,
      individualMandatePenalty: null,
      openEnrollmentStart: '11-01',
      openEnrollmentEnd: '01-31',
      hasExtendedEnrollment: true,
      allowsShortTermPlans: false,
      shortTermMaxDuration: 0,
      requiresNavigators: true,
      navigatorHotline: '1-855-355-5777',
      stateInsuranceDepartment: 'New York State Department of Financial Services',
      insuranceDepartmentWebsite: 'https://www.dfs.ny.gov',
      population: 20201249,
      totalCounties: 62,
      urbanPercentage: '87.00',
      dataYear: 2025,
      lastVerified: new Date(),
      notes: 'Community rating - premiums do not vary by age. Higher average premiums but more protections.',
    },
    {
      stateCode: 'AZ',
      stateName: 'Arizona',
      exchangeType: 'federal',
      exchangeName: 'Healthcare.gov',
      exchangeWebsite: 'https://www.healthcare.gov',
      exchangePhone: '1-800-318-2596',
      medicaidExpanded: true,
      medicaidExpansionDate: new Date('2014-01-01'),
      medicaidIncomeLimitAdults: '138.00',
      medicaidIncomeLimitChildren: '200.00',
      medicaidWebsite: 'https://www.azahcccs.gov',
      medicaidProgramName: 'AHCCCS (Arizona Health Care Cost Containment System)',
      chipIncomeLimitChildren: '200.00',
      chipWebsite: 'https://www.azahcccs.gov',
      chipProgramName: 'KidsCare',
      dominantCarriers: JSON.stringify([
        { name: 'Blue Cross Blue Shield of Arizona', marketShare: 32.5 },
        { name: 'Ambetter from Arizona Complete Health', marketShare: 24.8 },
        { name: 'Oscar Health', marketShare: 16.2 },
      ]),
      averageCarrierCount: 9,
      marketConcentration: 'medium',
      averagePremiumIndex: '0.980',
      averagePremiumSingleAdult: '455.00',
      averagePremiumFamily: '1265.00',
      individualMandate: false,
      individualMandatePenalty: null,
      openEnrollmentStart: '11-01',
      openEnrollmentEnd: '01-15',
      hasExtendedEnrollment: false,
      allowsShortTermPlans: true,
      shortTermMaxDuration: 364,
      requiresNavigators: false,
      navigatorHotline: '1-800-318-2596',
      stateInsuranceDepartment: 'Arizona Department of Insurance and Financial Institutions',
      insuranceDepartmentWebsite: 'https://difi.az.gov',
      population: 7151502,
      totalCounties: 15,
      urbanPercentage: '89.00',
      dataYear: 2025,
      lastVerified: new Date(),
      notes: 'Popular snowbird destination. High enrollment during winter months.',
    },
  ];

  await db.insert(states).values(statesData);
  console.log(`  ✓ Inserted ${statesData.length} state records`);

  console.log(`✅ Seeded carrier and state metadata`);
}
