CREATE TABLE "aca_plans" (
	"id" serial PRIMARY KEY NOT NULL,
	"state" varchar(2) NOT NULL,
	"county" varchar(100) NOT NULL,
	"rating_area" varchar(20) NOT NULL,
	"zip_code" varchar(5),
	"metal_tier" varchar(20) NOT NULL,
	"plan_type" varchar(20) NOT NULL,
	"carrier" varchar(100) NOT NULL,
	"plan_name" varchar(200) NOT NULL,
	"age" integer NOT NULL,
	"monthly_premium" numeric(10, 2) NOT NULL,
	"tobacco_surcharge" numeric(5, 2) NOT NULL,
	"deductible" numeric(10, 2) NOT NULL,
	"oop_maximum" numeric(10, 2) NOT NULL,
	"primary_care_visit" numeric(10, 2),
	"specialist_visit" numeric(10, 2),
	"network_tier" varchar(50),
	"national_network" boolean DEFAULT false,
	"plan_year" integer NOT NULL,
	"data_source" varchar(100) NOT NULL,
	"is_active" boolean DEFAULT true,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "add_on_insurance_costs" (
	"id" serial PRIMARY KEY NOT NULL,
	"state" varchar(2),
	"insurance_type" varchar(50) NOT NULL,
	"coverage_level" varchar(50) NOT NULL,
	"carrier" varchar(100),
	"plan_name" varchar(200),
	"monthly_premium_low" numeric(10, 2) NOT NULL,
	"monthly_premium_high" numeric(10, 2) NOT NULL,
	"annual_maximum" numeric(10, 2),
	"coverage_details" jsonb,
	"plan_year" integer NOT NULL,
	"is_active" boolean DEFAULT true,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "cost_adjustment_factors" (
	"id" serial PRIMARY KEY NOT NULL,
	"state" varchar(2) NOT NULL,
	"county" varchar(100),
	"geographic_cost_index" numeric(5, 3) NOT NULL,
	"is_urban" boolean DEFAULT true,
	"urban_multiplier" numeric(5, 3),
	"carrier_count" integer,
	"competition_index" numeric(5, 3),
	"effective_year" integer NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "employer_insurance_costs" (
	"id" serial PRIMARY KEY NOT NULL,
	"state" varchar(2) NOT NULL,
	"coverage_type" varchar(20) NOT NULL,
	"plan_type" varchar(20) NOT NULL,
	"average_monthly_premium" numeric(10, 2) NOT NULL,
	"employee_contribution" numeric(10, 2) NOT NULL,
	"employer_contribution" numeric(10, 2) NOT NULL,
	"average_deductible" numeric(10, 2) NOT NULL,
	"average_oop_maximum" numeric(10, 2) NOT NULL,
	"industry" varchar(100),
	"company_size" varchar(20),
	"data_year" integer NOT NULL,
	"data_source" varchar(100) NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "medicare_advantage_plans" (
	"id" serial PRIMARY KEY NOT NULL,
	"state" varchar(2) NOT NULL,
	"county" varchar(100) NOT NULL,
	"zip_code" varchar(5) NOT NULL,
	"plan_name" varchar(200) NOT NULL,
	"carrier" varchar(100) NOT NULL,
	"plan_type" varchar(20) NOT NULL,
	"monthly_premium" numeric(10, 2) NOT NULL,
	"medical_deductible" numeric(10, 2),
	"drug_deductible" numeric(10, 2),
	"oop_maximum" numeric(10, 2) NOT NULL,
	"dental_coverage" boolean DEFAULT false,
	"vision_coverage" boolean DEFAULT false,
	"hearing_coverage" boolean DEFAULT false,
	"part_d_coverage" boolean DEFAULT false,
	"service_area" jsonb,
	"network_size" varchar(20),
	"requires_referrals" boolean DEFAULT false,
	"star_rating" numeric(2, 1),
	"plan_year" integer NOT NULL,
	"contract_id" varchar(20) NOT NULL,
	"plan_id" varchar(20) NOT NULL,
	"is_active" boolean DEFAULT true,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "medicare_costs" (
	"id" serial PRIMARY KEY NOT NULL,
	"part_a_premium" numeric(10, 2) NOT NULL,
	"part_a_deductible" numeric(10, 2) NOT NULL,
	"part_b_premium" numeric(10, 2) NOT NULL,
	"part_b_deductible" numeric(10, 2) NOT NULL,
	"irmaa_tier" integer NOT NULL,
	"irmaa_threshold" numeric(12, 2) NOT NULL,
	"irmaa_amount" numeric(10, 2) NOT NULL,
	"plan_year" integer NOT NULL,
	"effective_date" timestamp NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "medigap_plans" (
	"id" serial PRIMARY KEY NOT NULL,
	"state" varchar(2) NOT NULL,
	"zip_code" varchar(5),
	"plan_letter" varchar(2) NOT NULL,
	"carrier" varchar(100) NOT NULL,
	"rating_method" varchar(20) NOT NULL,
	"age" integer,
	"gender" varchar(10),
	"tobacco" boolean DEFAULT false,
	"monthly_premium" numeric(10, 2) NOT NULL,
	"household_discount" numeric(5, 2),
	"plan_year" integer NOT NULL,
	"is_active" boolean DEFAULT true,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "part_d_plans" (
	"id" serial PRIMARY KEY NOT NULL,
	"state" varchar(2) NOT NULL,
	"region" varchar(50) NOT NULL,
	"plan_name" varchar(200) NOT NULL,
	"carrier" varchar(100) NOT NULL,
	"monthly_premium" numeric(10, 2) NOT NULL,
	"annual_deductible" numeric(10, 2) NOT NULL,
	"coverage_gap_discount" numeric(5, 2) NOT NULL,
	"formulary_tiers" integer NOT NULL,
	"preferred_pharmacy" boolean DEFAULT false,
	"mail_order_available" boolean DEFAULT false,
	"star_rating" numeric(2, 1),
	"plan_year" integer NOT NULL,
	"contract_id" varchar(20) NOT NULL,
	"plan_id" varchar(20) NOT NULL,
	"is_active" boolean DEFAULT true,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "slcsp_benchmarks" (
	"id" serial PRIMARY KEY NOT NULL,
	"state" varchar(2) NOT NULL,
	"county" varchar(100) NOT NULL,
	"rating_area" varchar(20) NOT NULL,
	"zip_code" varchar(5) NOT NULL,
	"age" integer NOT NULL,
	"slcsp_premium" numeric(10, 2) NOT NULL,
	"plan_year" integer NOT NULL,
	"effective_date" timestamp NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "adjacent_states" (
	"id" serial PRIMARY KEY NOT NULL,
	"state1" varchar(2) NOT NULL,
	"state2" varchar(2) NOT NULL,
	"border_miles" numeric(10, 2),
	"shared_carriers" jsonb,
	"network_overlap_score" integer,
	"cross_border_metros" jsonb,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "counties" (
	"id" serial PRIMARY KEY NOT NULL,
	"state_code" varchar(2) NOT NULL,
	"county_name" varchar(100) NOT NULL,
	"county_fips" varchar(5) NOT NULL,
	"rating_area" varchar(20) NOT NULL,
	"available_carriers" jsonb,
	"carrier_count" integer NOT NULL,
	"has_multiple_carriers" boolean NOT NULL,
	"average_silver_premium" numeric(10, 2),
	"slcsp_premium" numeric(10, 2),
	"has_national_networks" boolean DEFAULT false,
	"has_broad_networks" boolean DEFAULT false,
	"provider_density" varchar(20),
	"is_urban" boolean NOT NULL,
	"is_rural" boolean NOT NULL,
	"is_frontier_county" boolean DEFAULT false,
	"population" integer,
	"median_income" numeric(10, 2),
	"poverty_rate" numeric(5, 2),
	"uninsured_rate" numeric(5, 2),
	"data_year" integer NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "counties_county_fips_unique" UNIQUE("county_fips")
);
--> statement-breakpoint
CREATE TABLE "enrollment_deadlines" (
	"id" serial PRIMARY KEY NOT NULL,
	"state_code" varchar(2),
	"program_type" varchar(50) NOT NULL,
	"deadline_type" varchar(100) NOT NULL,
	"deadline_date" timestamp NOT NULL,
	"coverage_effective_date" timestamp,
	"notes" text,
	"urgent_deadline" boolean DEFAULT false,
	"year" integer NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "federal_poverty_levels" (
	"id" serial PRIMARY KEY NOT NULL,
	"year" integer NOT NULL,
	"state" varchar(2),
	"household_size" integer NOT NULL,
	"annual_income" numeric(10, 2) NOT NULL,
	"effective_date" timestamp NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "multi_state_carriers" (
	"id" serial PRIMARY KEY NOT NULL,
	"carrier_name" varchar(100) NOT NULL,
	"parent_company" varchar(100),
	"states" jsonb NOT NULL,
	"total_states" integer NOT NULL,
	"is_truly_national" boolean DEFAULT false,
	"has_network_reciprocity" boolean DEFAULT false,
	"reciprocity_details" text,
	"offers_aca" boolean DEFAULT false,
	"offers_medicare" boolean DEFAULT false,
	"offers_medicaid" boolean DEFAULT false,
	"offers_employer" boolean DEFAULT false,
	"website" varchar(500),
	"customer_service_phone" varchar(20),
	"plan_year" integer NOT NULL,
	"is_active" boolean DEFAULT true,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "provider_networks" (
	"id" serial PRIMARY KEY NOT NULL,
	"carrier" varchar(100) NOT NULL,
	"network_name" varchar(200) NOT NULL,
	"state_code" varchar(2) NOT NULL,
	"counties" jsonb,
	"network_type" varchar(50) NOT NULL,
	"network_size" varchar(20) NOT NULL,
	"total_providers" integer,
	"primary_care_count" integer,
	"specialist_count" integer,
	"hospital_count" integer,
	"meets_adequacy_standards" boolean DEFAULT true,
	"has_essential_community_providers" boolean DEFAULT false,
	"out_of_network_coverage" boolean DEFAULT false,
	"requires_referrals" boolean DEFAULT false,
	"telehealth" boolean DEFAULT false,
	"plan_year" integer NOT NULL,
	"is_active" boolean DEFAULT true,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "special_enrollment_periods" (
	"id" serial PRIMARY KEY NOT NULL,
	"state_code" varchar(2),
	"event_type" varchar(100) NOT NULL,
	"event_description" text NOT NULL,
	"sep_duration_days" integer NOT NULL,
	"coverage_effective_rule" varchar(200),
	"requires_documentation" boolean DEFAULT true,
	"documentation_types" jsonb,
	"retroactive_effective_date" boolean DEFAULT false,
	"special_instructions" text,
	"effective_year" integer NOT NULL,
	"is_active" boolean DEFAULT true,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "states" (
	"id" serial PRIMARY KEY NOT NULL,
	"state_code" varchar(2) NOT NULL,
	"state_name" varchar(100) NOT NULL,
	"exchange_type" varchar(50) NOT NULL,
	"exchange_name" varchar(200),
	"exchange_website" varchar(500),
	"exchange_phone" varchar(20),
	"medicaid_expanded" boolean NOT NULL,
	"medicaid_expansion_date" timestamp,
	"medicaid_income_limit_adults" numeric(5, 2),
	"medicaid_income_limit_children" numeric(5, 2),
	"medicaid_website" varchar(500),
	"medicaid_program_name" varchar(200),
	"chip_income_limit_children" numeric(5, 2),
	"chip_website" varchar(500),
	"chip_program_name" varchar(200),
	"dominant_carriers" jsonb,
	"average_carrier_count" integer,
	"market_concentration" varchar(20),
	"average_premium_index" numeric(5, 3),
	"average_premium_single_adult" numeric(10, 2),
	"average_premium_family" numeric(10, 2),
	"individual_mandate" boolean DEFAULT false,
	"individual_mandate_penalty" varchar(200),
	"open_enrollment_start" varchar(20),
	"open_enrollment_end" varchar(20),
	"has_extended_enrollment" boolean DEFAULT false,
	"allows_short_term_plans" boolean DEFAULT true,
	"short_term_max_duration" integer,
	"requires_navigators" boolean DEFAULT false,
	"navigator_hotline" varchar(20),
	"state_insurance_department" varchar(200),
	"insurance_department_website" varchar(500),
	"population" integer,
	"total_counties" integer,
	"urban_percentage" numeric(5, 2),
	"data_year" integer NOT NULL,
	"last_verified" timestamp,
	"notes" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "states_state_code_unique" UNIQUE("state_code")
);
--> statement-breakpoint
CREATE TABLE "subsidy_tables" (
	"id" serial PRIMARY KEY NOT NULL,
	"year" integer NOT NULL,
	"fpl_percentage_low" numeric(5, 2) NOT NULL,
	"fpl_percentage_high" numeric(5, 2) NOT NULL,
	"max_affordable_percentage" numeric(5, 2) NOT NULL,
	"is_enhanced" boolean DEFAULT false,
	"effective_date" timestamp NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "zip_code_mappings" (
	"id" serial PRIMARY KEY NOT NULL,
	"zip_code" varchar(5) NOT NULL,
	"state_code" varchar(2) NOT NULL,
	"county_fips" varchar(5) NOT NULL,
	"county_name" varchar(100) NOT NULL,
	"is_primary" boolean DEFAULT true,
	"city_name" varchar(100),
	"latitude" numeric(10, 7),
	"longitude" numeric(10, 7),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "analysis_sessions" (
	"id" serial PRIMARY KEY NOT NULL,
	"session_id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"user_agent" varchar(500),
	"ip_address_hash" varchar(64),
	"referrer" varchar(500),
	"states" jsonb NOT NULL,
	"household_size" integer,
	"age_ranges" jsonb,
	"has_tobacco_users" boolean,
	"has_employer_insurance" boolean,
	"income_bracket" varchar(50),
	"chronic_condition_count" integer,
	"prescription_count" varchar(20),
	"provider_preference" varchar(50),
	"recommendation_type" varchar(100),
	"estimated_cost_range" varchar(50),
	"subsidy_eligible" boolean,
	"calculator_completion_rate" integer,
	"steps_completed" integer,
	"time_spent_on_calculator" integer,
	"results_viewed" boolean DEFAULT false,
	"results_printed" boolean DEFAULT false,
	"results_shared" boolean DEFAULT false,
	"errors_encountered" jsonb,
	"session_started" timestamp DEFAULT now() NOT NULL,
	"session_ended" timestamp,
	"device_type" varchar(50),
	"browser_type" varchar(50),
	CONSTRAINT "analysis_sessions_session_id_unique" UNIQUE("session_id")
);
--> statement-breakpoint
CREATE TABLE "api_call_logs" (
	"id" serial PRIMARY KEY NOT NULL,
	"call_id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"api_name" varchar(100) NOT NULL,
	"endpoint" varchar(500) NOT NULL,
	"method" varchar(10) NOT NULL,
	"request_params" jsonb,
	"request_headers" jsonb,
	"status_code" integer NOT NULL,
	"response_time" integer,
	"success" boolean NOT NULL,
	"error_message" text,
	"error_code" varchar(100),
	"cache_hit" boolean DEFAULT false,
	"cache_ttl" integer,
	"rate_limit_remaining" integer,
	"rate_limit_reset" timestamp,
	"called_at" timestamp DEFAULT now() NOT NULL,
	"session_id" uuid,
	"estimated_cost" varchar(20),
	CONSTRAINT "api_call_logs_call_id_unique" UNIQUE("call_id")
);
--> statement-breakpoint
CREATE TABLE "audit_log" (
	"id" serial PRIMARY KEY NOT NULL,
	"audit_id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"table_name" varchar(100) NOT NULL,
	"record_id" integer NOT NULL,
	"operation" varchar(20) NOT NULL,
	"user_id" varchar(100),
	"user_email" varchar(255),
	"ip_address" varchar(50),
	"old_values" jsonb,
	"new_values" jsonb,
	"changed_fields" jsonb,
	"change_reason" text,
	"change_source" varchar(100),
	"timestamp" timestamp DEFAULT now() NOT NULL,
	"metadata" jsonb,
	CONSTRAINT "audit_log_audit_id_unique" UNIQUE("audit_id")
);
--> statement-breakpoint
CREATE TABLE "data_imports" (
	"id" serial PRIMARY KEY NOT NULL,
	"import_id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"import_name" varchar(200) NOT NULL,
	"data_source" varchar(200) NOT NULL,
	"data_type" varchar(100) NOT NULL,
	"file_name" varchar(500),
	"file_size" varchar(50),
	"file_hash" varchar(64),
	"status" varchar(50) NOT NULL,
	"started_at" timestamp DEFAULT now() NOT NULL,
	"completed_at" timestamp,
	"processing_time" integer,
	"rows_processed" integer,
	"rows_imported" integer,
	"rows_skipped" integer,
	"rows_failed" integer,
	"validation_errors" jsonb,
	"warnings" jsonb,
	"import_params" jsonb,
	"target_tables" jsonb,
	"imported_by" varchar(100),
	"import_method" varchar(50),
	"can_rollback" boolean DEFAULT true,
	"rollback_script" text,
	"rolled_back" boolean DEFAULT false,
	"rolled_back_at" timestamp,
	"logs" text,
	"metadata" jsonb,
	CONSTRAINT "data_imports_import_id_unique" UNIQUE("import_id")
);
--> statement-breakpoint
CREATE TABLE "data_quality_alerts" (
	"id" serial PRIMARY KEY NOT NULL,
	"alert_id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"severity" varchar(20) NOT NULL,
	"alert_type" varchar(100) NOT NULL,
	"title" varchar(200) NOT NULL,
	"description" text NOT NULL,
	"table_name" varchar(100) NOT NULL,
	"affected_records" jsonb,
	"affected_states" jsonb,
	"detected_at" timestamp DEFAULT now() NOT NULL,
	"detection_method" varchar(100),
	"status" varchar(50) NOT NULL,
	"resolved_at" timestamp,
	"resolved_by" varchar(100),
	"resolution_notes" text,
	"action_required" boolean DEFAULT false,
	"suggested_action" text,
	"notification_sent" boolean DEFAULT false,
	"notified_users" jsonb,
	"metadata" jsonb,
	CONSTRAINT "data_quality_alerts_alert_id_unique" UNIQUE("alert_id")
);
--> statement-breakpoint
CREATE TABLE "data_versions" (
	"id" serial PRIMARY KEY NOT NULL,
	"version_id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"version_name" varchar(200) NOT NULL,
	"description" text,
	"version_number" varchar(50) NOT NULL,
	"data_type" varchar(100) NOT NULL,
	"affected_tables" jsonb NOT NULL,
	"affected_states" jsonb,
	"status" varchar(50) NOT NULL,
	"is_production" boolean DEFAULT false,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"activated_at" timestamp,
	"deprecated_at" timestamp,
	"created_by" varchar(100),
	"data_snapshot" jsonb,
	"backup_location" varchar(500),
	"can_rollback" boolean DEFAULT true,
	"rollback_instructions" text,
	"is_validated" boolean DEFAULT false,
	"validation_errors" jsonb,
	"metadata" jsonb,
	CONSTRAINT "data_versions_version_id_unique" UNIQUE("version_id")
);
--> statement-breakpoint
CREATE TABLE "system_health_metrics" (
	"id" serial PRIMARY KEY NOT NULL,
	"metric_id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"metric_name" varchar(100) NOT NULL,
	"metric_value" varchar(100) NOT NULL,
	"metric_unit" varchar(50),
	"category" varchar(50) NOT NULL,
	"threshold" varchar(100),
	"exceeded_threshold" boolean DEFAULT false,
	"environment" varchar(50),
	"server_region" varchar(50),
	"recorded_at" timestamp DEFAULT now() NOT NULL,
	"metadata" jsonb,
	CONSTRAINT "system_health_metrics_metric_id_unique" UNIQUE("metric_id")
);
